FROM python:3.14-alpine

ENV MUSL_LOCPATH=/usr/share/i18n/locales/musl \
    LANG="C.UTF-8" \
    LANGUAGE="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    PATH="/home/hello/.local/bin:${PATH}"

# hadolint ignore=DL3003
RUN apk add --no-cache \
        libintl \
        openssl && \
    apk --no-cache add --virtual build-dependencies \
        cmake \
        make \
        musl \
        musl-dev \
        musl-utils \
        gcc \
        gettext-dev && \
    wget -q https://gitlab.com/rilian-la-te/musl-locales/-/archive/master/musl-locales-master.zip && \
    unzip musl-locales-master.zip && cd musl-locales-master && \
    cmake -DLOCALE_PROFILE=OFF -D CMAKE_INSTALL_PREFIX:PATH=/usr . && \
    make && make install && \
    cd .. && rm -r musl-locales-master && \
    adduser -D hello && \
    apk del build-dependencies

WORKDIR /opt/app
COPY api/ api/
COPY test/requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt && chmod -R 777 /opt/app

ENTRYPOINT ["uvicorn", "api.main:api", "--host", "0.0.0.0", "--port", "8000"]
